name: shopzz_flutter_app
description: shopzz flutter app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  oktoast: ^3.1.5
  dio: ^3.0.10
  pull_to_refresh: ^2.0.0
  get: ^4.6.1
  lottie: ^1.2.1
  shared_preferences: ^2.0.5
  connectivity: ^3.0.6
  cached_network_image: ^2.4.1
  event_bus: ^2.0.0
  geolocator: ^5.1.3
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  qr_flutter: ^4.0.0
  #barcode_scan2: ^4.2.0
  video_player: ^2.1.1
  marquee: ^2.1.0
  like_button: ^2.0.2
  skeletons: ^0.0.3
  device_info_plus: 3.1.1
  roundcheckbox: ^2.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/