server:
  port: 8007

spring:
  application:
    name: zz-order-web
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: aliyun.whoiszxl.com:8848
      config:
        server-addr: aliyun.whoiszxl.com:8848
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.198.122/shopzz?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: shopzz
    password: ECmzyDLN7bRSKtab

    hikari:
      connection-timeout: 10000
      max-lifetime: 60000

  redis:
    host: 47.103.198.122
    port: 6379
    password: ECmzyDLN7bRSKtab
    timeout: 6000ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

seesee:
  swagger2:
    enabled: true
    title: order-在线接口文档
    base-package: com.whoiszxl.controller
  log:
    enabled: true

logging:
  config: classpath:logback-spring.xml

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false

  # 配置Sa-Token单独使用的Redis连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 47.103.198.122
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ECmzyDLN7bRSKtab
    # 连接超时时间（毫秒）
    timeout: 6000ms

feign:
  httpclient:
    connection-timeout: 40000
    read-timeout: 40000

ribbon:
  ReadTimeout: 40000
  ConnectTimeout: 40000

jasypt:
  encryptor:
    password: 123456 #配置EncryptPropertiesUtils工具类里填写的秘钥

dozer:
  mapping-files:
    - classpath:dozer/biz.dozer.xml

